services:
  app:
    build: .
    environment:
      - FLASK_APP=api
    command: bash -c "python -m pytest --cov=api test && python -m flask run --host 0.0.0.0"
    ports:
      - "5001:5000"
    volumes:
      - .:/python-flask